analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5702128
  lightness: 0.5127659
  brandStrength: 0.5872327813412994
  brandColors:
    - '#DED9CF'
    - '#202630'
    - '#A4C5F2'
    - '#7899D1'
    - '#535B6E'
  rhythmicContrast: 0.5489362
typography_spectrum: 0.8276595
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.8765957
favicon: null
name: Make Reception
