favicon: null
name: Make Reception
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.0812944935169071
  brandStrength: 0.5872327813412994
  lightness: 0.273523025913164
  brandColors:
    - '#DED9CF'
    - '#202630'
    - '#A4C5F2'
    - '#7899D1'
    - '#535B6E'
  rhythmicContrast: 0.3709327871911228
typography_spectrum: 0.05875915801152587
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.4138415632769465
analytics:
  twitter: null
  google: null
  facebook: null
